ALTER TABLE files
    RENAME COLUMN others_read TO group_read;
ALTER TABLE files
    RENAME COLUMN others_write TO group_write;

ALTER TABLE files
    ADD COLUMN group_execute  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN user_read      BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN user_write     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN user_execute   BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN others_read    BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN others_write   BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN others_execute BOOLEAN NOT NULL DEFAULT FALSE;